services:
  - type: web
    name: reputationsync-dashboard
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn_conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        value: dashboard.db
    healthCheckPath: /health
    autoDeploy: true 